config/routes.rb
Rails.application.routes.draw do
  resources :subtasks
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :tasks, :subtasks
  end
  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task

  after_update :check_completed_subtasks

  def check_completed_subtasks
    # byebug
    task.update_done_status
  end
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true

  scope :done, -> { where(done: true) }

  has_many :subtasks

  def update_done_status
    if subtasks.all?(&:done)
      update_attribute(:done, true)
    else
      update_attribute(:done, false)
    end
  end
end

app/controllers/admin/subtasks_controller.rb
class Admin::SubtasksController < ApplicationController
  before_action :authenticate
  before_action :set_subtask, only: %i[ show edit update destroy ]

  # GET /subtasks or /subtasks.json
  def index
    @subtasks = Subtask.all
  end

  # GET /subtasks/1 or /subtasks/1.json
  def show
  end

  # GET /subtasks/new
  def new
    @subtask = Subtask.new
  end

  # GET /subtasks/1/edit
  def edit
  end

  # POST /subtasks or /subtasks.json
  def create
    @subtask = Subtask.new(subtask_params)

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to admin_subtask_url(@subtask), notice: "Subtask was successfully created." }
        format.json { render :show, status: :created, location: @subtask }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtasks/1 or /subtasks/1.json
  def update
    respond_to do |format|
      if @subtask.update(subtask_params)
        format.html { redirect_to subtask_url(@subtask), notice: "Subtask was successfully updated." }
        format.json { render :show, status: :ok, location: @subtask }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtasks/1 or /subtasks/1.json
  def destroy
    @subtask.destroy

    respond_to do |format|
      format.html { redirect_to subtasks_url, notice: "Subtask was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subtask_params
      params.require(:subtask).permit(:title, :description, :done, :completed_at, :task_id)
    end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username === "admin" && password === "secret"
    end
  end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
    before_action :authenticate
    before_action :set_task, only: %i[ show edit update destroy ]

    def index
      @tasks = Task.all
    end

    # GET /tasks/1 or /tasks/1.json
    def show
    end

    # GET /tasks/new
    def new
      @task = Task.new
    end
  
    # GET /tasks/1/edit
    def edit
    end
  
    # POST /tasks or /tasks.json
    def create
      @task = Task.new(task_params)
  
      respond_to do |format|
        if @task.save
          format.html { redirect_to admin_task_url(@task), notice: "Task was successfully created." }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /tasks/1 or /tasks/1.json
    def update
      respond_to do |format|
        if @task.update(task_params)
          format.html { redirect_to admin_task_url(@task), notice: "Task was successfully updated." }
          format.json { render :show, status: :ok, location: @task }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /tasks/1 or /tasks/1.json
    def destroy
      @task.destroy
  
      respond_to do |format|
        format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, :done, :completed_at)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username === "admin" && password === "secret"
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_subtask, only: %i[ show edit update destroy ]

  # GET /subtasks or /subtasks.json
  def index
    @subtasks = Subtask.all

    render :json => @subtasks
  end

  # GET /subtasks/1 or /subtasks/1.json
  def show
    render :json => @subtask
  end

  # POST /subtasks or /subtasks.json
  def create
    @subtask = Subtask.new(subtask_params)

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to subtask_url(@subtask), notice: "Subtask was successfully created." }
        format.json { render :show, status: :created, location: @subtask }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtasks/1 or /subtasks/1.json
  def update
    respond_to do |format|
      if @subtask.update(subtask_params)
        format.html { redirect_to subtask_url(@subtask), notice: "Subtask was successfully updated." }
        format.json { render :show, status: :ok, location: @subtask }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtasks/1 or /subtasks/1.json
  def destroy
    @subtask.destroy

    respond_to do |format|
      format.html { redirect_to subtasks_url, notice: "Subtask was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subtask_params
      params.require(:subtask).permit(:title, :description, :done, :completed_at, :task_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = filter_params[:is_done] ? Task.done : Task.all

    render :json => @tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    render :json => @task
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def task_params
    #   params.require(:task).permit(:title, :description, :done, :completed_at)
    # end

    def filter_params
      params.permit(:is_done)
    end
end

app/helpers/admin/subtasks_helper.rb
module Admin::SubtasksHelper
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/subtasks/_form.html.erb
<%= form_with(model: [:admin, subtask]) do |form| %>
  <% if subtask.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
        <% subtask.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :done, style: "display: block" %>
    <%= form.check_box :done %>
  </div>

  <div>
    <%= form.label :completed_at, style: "display: block" %>
    <%= form.datetime_field :completed_at %>
  </div>

  <div>
    <%= form.label :task_id, style: "display: block" %>
    <%= form.text_field :task_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/subtasks/_subtask.html.erb
<div id="<%= dom_id subtask %>">
  <p>
    <strong>Title:</strong>
    <%= subtask.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= subtask.description %>
  </p>

  <p>
    <strong>Done:</strong>
    <%= subtask.done %>
  </p>

  <p>
    <strong>Completed at:</strong>
    <%= subtask.completed_at %>
  </p>

  <p>
    <strong>Task:</strong>
    <%= subtask.task_id %>
  </p>

</div>

app/views/admin/subtasks/edit.html.erb
<h1>Editing subtask</h1>

<%= render "form", subtask: @subtask %>

<br>

<div>
  <%= link_to "Show this subtask", admin_subtask_path(@subtask) %> |
  <%= link_to "Back to subtasks", admin_subtasks_path %>
</div>

app/views/admin/subtasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subtasks</h1>

<div id="subtasks">
  <% @subtasks.each do |subtask| %>
    <%= render subtask %>
    <p>
      <%= link_to "Show this subtask", admin_subtask_path(subtask) %>
    </p>
  <% end %>
</div>

<%= link_to "New subtask", new_admin_subtask_path %>

app/views/admin/subtasks/new.html.erb
<h1>New subtask</h1>

<%= render "form", subtask: @subtask %>

<br>

<div>
  <%= link_to "Back to subtasks", admin_subtasks_path %>
</div>

app/views/admin/subtasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subtask %>

<div>
  <%= link_to "Edit this subtask", edit_admin_subtask_path(@subtask) %> |
  <%= link_to "Back to subtasks", admin_subtasks_path %>

  <%= button_to "Destroy this subtask", @subtask, method: :delete %>
</div>

app/views/admin/tasks/_form.html.erb
<%= form_with(model: [:admin, task]) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :done, style: "display: block" %>
    <%= form.check_box :done %>
  </div>

  <div>
    <%= form.label :completed_at, style: "display: block" %>
    <%= form.datetime_field :completed_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Title:</strong>
    <%= task.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Done:</strong>
    <%= task.done %>
  </p>

  <p>
    <strong>Completed at:</strong>
    <%= task.completed_at %>
  </p>

</div>

app/views/admin/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", admin_tasks_path %>
</div>

app/views/admin/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", admin_task_path(task) %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_admin_task_path %>

app/views/admin/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", admin_tasks_path %>
</div>

app/views/admin/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_admin_task_path(@task) %> |
  <%= link_to "Back to tasks", admin_tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Task Manager</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Tasks", admin_tasks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Subtasks", admin_subtasks_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>